Traceback (most recent call last):
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
assert GBP(1, -19, 0) == GBP(0, 1, 0) # This is fine

import pytest
with pytest.raises(NegativePounds):
    GBP(1, -21, 0) # Not fine
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNegativePounds[0m                            Traceback (most recent call last)
Cell [0;32mIn[18], line 5[0m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpytest[39;00m
[1;32m      4[0m [38;5;28;01mwith[39;00m pytest[38;5;241m.[39mraises(NegativePounds):
[0;32m----> 5[0m     [43mGBP[49m[43m([49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[38;5;241;43m-[39;49m[38;5;241;43m21[39;49m[43m,[49m[43m [49m[38;5;241;43m0[39;49m[43m)[49m [38;5;66;03m# Not fine[39;00m

File [0;32m~/courses/bb1000/exams/gh/solutions.py:129[0m, in [0;36mGBP.__init__[0;34m(self, pounds, shillings, pence)[0m
[1;32m    127[0m [38;5;66;03m# 8. raise exception for negative amounts[39;00m
[1;32m    128[0m [38;5;28;01mif[39;00m to_pence([38;5;241m*[39m[38;5;28mself[39m[38;5;241m.[39mdata) [38;5;241m<[39m [38;5;241m0[39m:
[0;32m--> 129[0m     [38;5;28;01mraise[39;00m NegativePounds

[0;31mNegativePounds[0m: 

